server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute #identificando la ruta del servicio
          uri: http://movie-service #http://localhost:8082/ #url o nombre registrado en eureka donde se hara el redirect segun el predicate definido
          predicates: #reglas de analisis de una request
            - Path=/movies/**
        - id: catalogRoute #identificando la ruta del servicio
          uri: http://localhost:8084/
          predicates: 
            - Path=/catalog/**
 #las configuraciones del registro en eureka las toma del application.yml
       
          
