server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:movie.sql
  jpa:
    defer-datasource-initialization: true
    hibertbate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false

info:
  app:
    name: movie-service
    description: Movie Service created for DH
    version: 1.0.0
        
